channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - python>=3.8,<3.9
  - pip
  # Essentials
  - boto3
  - dynaconf
  - pandas
  - numpy
  - scipy
  # Jupyter - Lab, Notebook, ipykernel
  - jupyterlab 
  - ipykernel
  # Streamlit and friends
  - streamlit>=1.0
# - pip:
#   - TODO
