[APP]
DATASOURCE = 'Not applicable - using API'
AUTHOR = '[Michael @ DataBooth.com.au](https://www.databooth.com.au)'
NAME = 'ASX Share Price lookup app' 
CACHED_DATAFILE = 'TBA.format'
LAYOUT = 'wide'

[S3] # Cloud Object Storage: https://console.scaleway.com
ACCESS_KEY_ID = 'SCW5MSNHMS37P6Q0ZZV2'   # Credentials
SECRET_ACCESS_TOML = 'st-app-secrets.toml'
STORAGE_BUCKET_NAME = 'personal-tan-lea-kuan'
DEFAULT_ACL = 'public-read'
REGION_NAME = 'fr-par'
ENDPOINT_URL = 'https://s3.fr-par.scw.cloud'
